-- 添加 clusters 表缺失的字段
ALTER TABLE clusters
ADD COLUMN IF NOT EXISTS provider VARCHAR(100) DEFAULT '太初',
ADD COLUMN IF NOT EXISTS region VARCHAR(100),
ADD COLUMN IF NOT EXISTS last_backup_at TIMESTAMP WITH TIME ZONE NULL,
ADD COLUMN IF NOT EXISTS environment_type VARCHAR(50) DEFAULT 'production',
ADD COLUMN IF NOT EXISTS import_source VARCHAR(100);
